### ISSUE TITLE
Summary of issues with the repo interface

### ISSUE THREAD

**Issue by jlegind** [gbif/data-repo#5]
* No indication of what fields in the form are mandatory
* No useful error message when submitting the upload
* No ‘on the fly error handling’
*	The RELATED IDENTIFIERS section needs some documentation/user-help for outside contributors to the repo
    *	Only relations supported by DataCite are allowed which is fine. The documentation[1] is quite extensive though and not suitable for all outside users.
* Providing your ORCID prevents a successful upload. Leaving the ORCID empty works.
* The ABOUT section (top menu bar) contains placeholder data (“Lorem ipsum …”)
* REMINDER: The DOI issued in UAT is not resolving/valid, for understandable reasons, but it needs to be valid for the production version of the tool.

[1] http://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf

**Comment by MortenHofft** [comment]
Thanks for compiling these.

**No useful error message when submitting the upload**
Relates to https://github.com/gbif/data-repo/issues/3
Error messages is shown as is from the API, so changing the API error response should fix this.

**No ‘on the fly error handling’**
Could you elaborate on what this means please?

**The RELATED IDENTIFIERS section needs some documentation**
If someone writes an article or FAQ item, then we can link to that.

**Providing your ORCID prevents a successful upload. Leaving the ORCID empty works.**
also captured in https://github.com/gbif/data-repo/issues/4

**The ABOUT section (top menu bar) contains placeholder data (“Lorem ipsum …”)**
The article that needs writing is here: https://app.contentful.com/spaces/uo17ejk9rkwj/entries/33ZlEJM58I4iMqSqCiiQgg

**No indication of what fields in the form are mandatory**
Required fields are marked with an * or says required. If you don't fill them they will be marked in red. Let me know how else you believe they should be marked.

![screen shot 2018-08-16 at 09 46 49](https://user-images.githubusercontent.com/6759267/44195512-946a4380-a139-11e8-8993-08894a64d999.png)

** ... not suitable for all outside users**
I guess this is also a discussion about scope. Last I heard this was only intended as a tool for you @jlegind and perhaps a select few others that were invited.

**Comment by jlegind** [comment]
@MortenHofft By 'On the fly...' I mean checking the input in the field as soon as it is inputted (_before_ 
 pressing submit), so that invalid data is caught right away.
This is more nice to have rather than need-to-have

**Comment by MortenHofft** [comment]
I'm not sure I get how this relates the the data repo? Wrong issue perhaps?

**Comment by jlegind** [comment]
ouch - yes 
Moving it to https://github.com/gbif/registry/issues/56#issuecomment-418338110

**Comment by jlegind** [comment]
Issue has become obsolete with the Zenodo workflow:
https://gbif.app.box.com/file/553571967044?s=axlv30iyx2w4r1g2vqsg010a3xdfq5q9
